"""Analyze the frozen k-anonymous microaggregation application test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/privacy_microaggregation_report.md"
STUDY = "granular-ball-application-privacy-microaggregation"
DATASETS = ("breast_cancer", "wine", "digits", "covertype")
METHODS = ("granular_ball", "kmeans_merge", "mdav", "axis_tree", "random_groups")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [json.loads(line) for line in RESULTS.read_text().splitlines() if line]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 12 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 12 successful records, got {len(records)}")
    summary = {}
    for dataset in DATASETS:
        subset = [record for record in records if record["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {}
        for method in METHODS:
            values = [
                next(point for point in record["additional_metrics"]["frontier"] if point["method"] == method and point["k"] == 10)
                for record in subset
            ]
            summary[dataset][method] = {
                "distortion": mean(point["distortion_mse"] for point in values),
                "accuracy": mean(point["downstream_accuracy"] for point in values),
                "milliseconds": 1000 * mean(point["runtime_seconds"] for point in values),
            }
    distortion_gain = mean(
        record["additional_metrics"]["relative_distortion_gain_vs_best"] for record in records
    )
    accuracy_gap = mean(record["additional_metrics"]["accuracy_gap_vs_best"] for record in records)
    distortion_passes = sum(
        record["additional_metrics"]["relative_distortion_gain_vs_best"] >= 0.05
        for record in records
    )
    accuracy_passes = sum(record["additional_metrics"]["accuracy_gap_vs_best"] >= 0.01 for record in records)
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['distortion']:.3f}" for method in METHODS)
        + f" | {summary[dataset]['granular_ball']['accuracy']:.3f} |"
        for dataset in DATASETS
    )
    report = f"""# GB application: k-anonymous microaggregation

Generated by `python scripts/analyze_app_privacy_microaggregation.py`. Audit
date: 2026-08-25.

## Decision

**`REJECT`.** Under equal `k=10` anonymity, GB distortion is
{abs(distortion_gain):.1%} worse than the best microaggregation baseline and
downstream balanced accuracy is {abs(accuracy_gap):.2%} lower on average. The
+5% distortion gate passes {distortion_passes}/12 and +1 pp utility gate passes
{accuracy_passes}/12.

## Frozen evidence

- Four numerical classification datasets x three seeds, capped at 1,000 rows.
- Every released quasi-identifier is replaced by its group centroid; every group
  has at least k records.
- Baselines: KMeans with small-cluster merge, MDAV, axis partition and random
  groups. Privacy k values are 5, 10 and 20.
- A fixed LogisticRegression evaluates clean held-out utility.

| Dataset | GB distortion | KMeans | MDAV | Axis | Random | GB utility |
|---|---:|---:|---:|---:|---:|---:|
{table}

MDAV or merged KMeans minimizes distortion on all primary datasets. Isolated GB
utility gains do not compensate for substantially larger information loss.
This is k-anonymity only, not differential privacy or attribute-disclosure
protection. Do not extend to t-closeness/DP.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "distortion_gain": distortion_gain, "accuracy_gap": accuracy_gap, "distortion_passes": distortion_passes, "accuracy_passes": accuracy_passes, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
