"""Analyze the frozen point-cloud compression/retrieval application test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/pointcloud_compression_report.md"
STUDY = "granular-ball-application-pointcloud-compression"
REGIMES = ("uniform", "density_bias", "outliers", "occlusion")
METHODS = ("granular_ball", "kmeans", "fps", "axis_cells", "random", "full")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [json.loads(line) for line in RESULTS.read_text().splitlines() if line]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 12 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 12 successful records, got {len(records)}")
    summary = {}
    for regime in REGIMES:
        subset = [record for record in records if record["dataset_generation_parameters"]["regime"] == regime]
        summary[regime] = {}
        for method in METHODS:
            values = [
                next(
                    point
                    for point in record["additional_metrics"]["frontier"]
                    if point["method"] == method and (method == "full" or point["budget"] == 64)
                )
                for record in subset
            ]
            summary[regime][method] = {
                "map": mean(point["map_at_10"] for point in values),
                "accuracy": mean(point["knn_accuracy"] for point in values),
                "chamfer": mean(point["mean_chamfer"] for point in values),
                "seconds": mean(point["compression_seconds"] for point in values),
            }
    map_gap = mean(record["additional_metrics"]["map_gap_vs_best"] for record in records)
    chamfer_gain = mean(record["additional_metrics"]["relative_chamfer_gain_vs_best"] for record in records)
    map_passes = sum(record["additional_metrics"]["map_gap_vs_best"] >= 0.01 for record in records)
    chamfer_passes = sum(
        record["additional_metrics"]["relative_chamfer_gain_vs_best"] >= 0.05
        for record in records
    )
    table = "\n".join(
        f"| {regime} | "
        + " | ".join(f"{summary[regime][method]['map']:.3f}" for method in METHODS)
        + f" | {summary[regime]['granular_ball']['chamfer']:.3f} |"
        for regime in REGIMES
    )
    report = f"""# GB application: point-cloud compression and shape retrieval

Generated by `python scripts/analyze_app_pointcloud_compression.py`. Audit date:
2026-08-25.

## Decision

**`REJECT`.** At 64/256 points, GB trails the strongest equal-budget retrieval
baseline by {abs(map_gap):.3f} mAP@10 and its Chamfer error is
{abs(chamfer_gain):.1%} worse than the strongest baseline on average. The +1 pp
mAP gate passes {map_passes}/12 and +5% Chamfer gate passes
{chamfer_passes}/12.

## Frozen evidence

- Five synthetic shape classes, four sampling/corruption regimes and three
  seeds; 32/64/128-point budgets.
- Weighted GB centers are compared with weighted KMeans centers, farthest-point
  sampling, axis cells, random points and the full cloud.
- All methods feed the same covariance/radial/pairwise-distance descriptor and
  exact shape-gallery retrieval.

| Regime | GB mAP | KMeans | FPS | Axis | Random | Full | GB Chamfer |
|---|---:|---:|---:|---:|---:|---:|---:|
{table}

FPS is markedly stronger on uniform, density-biased and occluded clouds.
KMeans/axis partitions remain competitive under outliers. GB compression is also
slow: roughly 3-5 seconds per 50-object dataset at the primary budget, versus
0.02-0.04 seconds for FPS and 0.26-0.46 seconds for KMeans.

The direct accepted GB collision remains registration (GRICP), not compression,
but generic point sampling is sufficient to reject this mechanism. Do not expand
to ModelNet/ScanObjectNN.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "map_gap": map_gap, "chamfer_gain": chamfer_gain, "map_passes": map_passes, "chamfer_passes": chamfer_passes, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
