"""Analyze the frozen matched batch active-learning application test."""

from __future__ import annotations

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/active_learning_report.md"
STUDY = "granular-ball-application-active-learning"
DATASETS = ("iris", "wine", "breast_cancer", "digits", "moons")
SEEDS = (1, 7, 21, 42, 2026)
METHODS = (
    "gb_radius_batch",
    "gb_center_batch",
    "kmeans_batch",
    "entropy",
    "kcenter",
    "random",
)


def mean(values):
    return statistics.fmean(values)


def method_row(record, method):
    return next(row for row in record["additional_metrics"]["methods"] if row["method"] == method)


def load():
    records = [
        json.loads(line)
        for line in RESULTS.read_text(encoding="utf-8").splitlines()
        if line
    ]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 25 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 25 successful records, got {len(records)}")
    observed = {
        (record["dataset_generation_parameters"]["dataset"], int(record["seed"]))
        for record in records
    }
    if observed != {(dataset, seed) for dataset in DATASETS for seed in SEEDS}:
        raise ValueError("active-learning grid mismatch")
    return records


def main():
    records = load()
    summary = {}
    for dataset in DATASETS:
        subset = [r for r in records if r["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {
            method: {
                "accuracy_auc": mean(method_row(r, method)["accuracy_auc"] for r in subset),
                "final_accuracy": mean(method_row(r, method)["curve"][-1]["accuracy"] for r in subset),
                "query_ms": 1000 * mean(method_row(r, method)["query_seconds"] for r in subset),
            }
            for method in METHODS
        }
    gaps = [r["additional_metrics"]["accuracy_auc_gap_vs_best_reference"] for r in records]
    ablation_gaps = [
        r["additional_metrics"]["accuracy_auc_gap_vs_center_ablation"] for r in records
    ]
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['accuracy_auc']:.3f}" for method in METHODS)
        + " |"
        for dataset in DATASETS
    )
    report = f"""# GB application: batch active learning

Generated by `python scripts/analyze_app_active_learning.py` from the append-only
ledger. Audit date: 2026-08-25.

## Decision

**`REJECT`.** Radius-aware GB batches trail the strongest per-run selector by
{abs(mean(gaps)):.3f} label-budget Accuracy AUC on average. Only
{sum(gap >= .005 for gap in gaps)}/25 runs clear the +.5 pp gate. Against the
identical bisecting partition with entropy-only point choice, radius weighting is
{mean(ablation_gaps):+.3f} on average and clears +.5 pp in only
{sum(gap >= .005 for gap in ablation_gaps)}/25.

## Frozen protocol

- Five datasets x five seeds = 25 successful CPU runs.
- Initial labels: two per class. Curves are evaluated near 2%, 5%, 10% and 20%
  labeled data, always on a fixed held-out test split.
- Unseen pool labels are used only after selection.
- GB radius and center ablation share the same recursive 2-means groups. Matched
  controls are flat KMeans batches, entropy, k-center and random selection.

Mean normalized Accuracy AUC over label budget:

| Dataset | GB radius | Same-partition center | KMeans | Entropy | k-center | Random |
|---|---:|---:|---:|---:|---:|---:|
{table}

Iris is the only positive dataset-level signal: GB radius reaches
{summary['iris']['gb_radius_batch']['accuracy_auc']:.3f}, about
{summary['iris']['gb_radius_batch']['accuracy_auc'] - max(summary['iris'][m]['accuracy_auc'] for m in METHODS[1:]):+.3f}
over the strongest mean reference. It does not transfer. On breast cancer and
digits, the same-partition center ablation is better by
{summary['breast_cancer']['gb_center_batch']['accuracy_auc'] - summary['breast_cancer']['gb_radius_batch']['accuracy_auc']:.3f}
and {summary['digits']['gb_center_batch']['accuracy_auc'] - summary['digits']['gb_radius_batch']['accuracy_auc']:.3f}.

GB querying is also not a latency win: on digits it uses about
{summary['digits']['gb_radius_batch']['query_ms']:.1f} ms across rounds, versus
{summary['digits']['kmeans_batch']['query_ms']:.1f} ms for KMeans and effectively
zero for point entropy.

## Kill rationale

- The +.5 pp gate does not hold across three datasets or four of five seeds.
- Radius weighting loses to the identical partition without radius on average.
- The only positive aggregate is the smallest classic dataset, Iris.
- Generic batch AL, clustering and coreset selection are heavily occupied; a
  one-dataset GB partition effect has no novelty or application sufficiency.

No query-score tuning, larger benchmark, or deep feature extractor is justified.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "mean_gap": mean(gaps), "ablation_gap": mean(ablation_gaps), "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
