"""Analyze the frozen fixed-memory GB drift-sketch application test."""

from __future__ import annotations

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/drift_sketch_report.md"
STUDY = "granular-ball-application-drift-sketch"
SHIFTS = ("translation", "local_emergence", "variance", "mixture_weight")
SEEDS = (1, 7, 21, 42, 2026)


def mean(values):
    return statistics.fmean(values)


def row(record, method, budget=16):
    matches = [
        item
        for item in record["additional_metrics"]["frontier"]
        if item["method"] == method
        and (method == "full_mmd" or int(item["budget"]) == budget)
    ]
    if len(matches) != 1:
        raise ValueError(f"{record['experiment_id']}: missing {method}/{budget}")
    return matches[0]


def load():
    records = [
        json.loads(line)
        for line in RESULTS.read_text(encoding="utf-8").splitlines()
        if line
    ]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 20 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 20 successful records, got {len(records)}")
    observed = {
        (record["dataset_generation_parameters"]["shift_kind"], int(record["seed"]))
        for record in records
    }
    expected = {(shift, seed) for shift in SHIFTS for seed in SEEDS}
    if observed != expected or len({record["experiment_id"] for record in records}) != 20:
        raise ValueError("frozen drift-sketch grid mismatch")
    return records


def main():
    records = load()
    methods = ("granular_ball", "kmeans", "reservoir_mmd", "full_mmd")
    summaries = {}
    for shift in SHIFTS:
        subset = [
            record
            for record in records
            if record["dataset_generation_parameters"]["shift_kind"] == shift
        ]
        summaries[shift] = {
            method: {
                "auroc": mean(row(record, method)["auroc"] for record in subset),
                "fpr": mean(row(record, method)["false_positive_rate"] for record in subset),
                "memory": mean(row(record, method)["memory_bytes"] for record in subset),
                "query_us": 1e6
                * mean(row(record, method)["mean_query_seconds"] for record in subset),
            }
            for method in methods
        }
    gaps = [record["additional_metrics"]["auroc_gap_vs_best_equal_memory"] for record in records]
    memory_reduction = mean(
        record["additional_metrics"]["memory_reduction_vs_full_mmd"]
        for record in records
    )
    table = "\n".join(
        f"| {shift} | "
        + " | ".join(f"{summaries[shift][method]['auroc']:.3f}" for method in methods)
        + " |"
        for shift in SHIFTS
    )
    report = f"""# GB application: fixed-memory drift sketch

Generated by `python scripts/analyze_app_drift_sketch.py` from the append-only
ledger. Audit date: 2026-08-25.

## Decision

**`REJECT`.** The granular-ball sketch does not provide a unique distribution-
monitoring advantage. At the fixed 16-unit budget it trails the best equal-memory
KMeans/reservoir baseline by {abs(mean(gaps)):.3f} AUROC on average and clears a
+.02 AUROC gate in only {sum(gap >= .02 for gap in gaps)}/20 runs.

## Frozen test

- Edge-monitoring application: compress a 1,200-row reference distribution into
  centers, 95% radii and occupancy weights.
- Four shift families x five seeds = 20 successful CPU runs.
- Granular-ball and KMeans sketches use exactly 1,024 bytes at budget 16.
- Reservoir MMD uses 1,008 bytes; full MMD stores 28,800 bytes.
- Thresholds use separate clean calibration batches. Evaluation includes clean
  false positives and five unseen drift severities.

Mean AUROC over five seeds:

| Shift | GB | KMeans | Reservoir MMD | Full MMD |
|---|---:|---:|---:|---:|
{table}

KMeans beats the GB sketch on mean AUROC in all four shifts. The largest GB
signal is local emergence ({summaries['local_emergence']['granular_ball']['auroc']:.3f}),
but KMeans reaches {summaries['local_emergence']['kmeans']['auroc']:.3f} with the
same bytes. On translation, GB reaches only
{summaries['translation']['granular_ball']['auroc']:.3f}, versus
{summaries['translation']['reservoir_mmd']['auroc']:.3f} for equal-memory
reservoir MMD.

## Resource result

GB reduces stored bytes by {100 * memory_reduction:.1f}% versus full MMD and
queries in about {mean(summaries[s]['granular_ball']['query_us'] for s in SHIFTS):.1f}
microseconds per batch, versus
{mean(summaries[s]['full_mmd']['query_us'] for s in SHIFTS):.1f} microseconds for
full MMD. This does not rescue the candidate: matched KMeans uses identical
memory, comparable query time, and better detection. The resource gain belongs
to prototype compression generally, not granular balls specifically.

## Kill rationale

- No stable Accuracy/AUROC advantage over equal-memory non-GB methods.
- No unique memory or latency advantage over matched KMeans.
- Only synthetic evidence; expansion to real streams is unjustified after the
  equal-budget gate fails.
- Changing weights, radii or score coefficients after observing this grid would
  be post-hoc mechanism search on the evaluation set.

No tuning or real-data expansion is allowed. The next application candidate is
contextual cell-error cleaning, where granular balls act as multiscale local
contexts rather than generic distribution prototypes.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "mean_gap": mean(gaps), "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
