"""Analyze the frozen model failure-slice discovery test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/failure_slices_report.md"
STUDY = "granular-ball-application-failure-slices"
DATASETS = ("moons", "breast_cancer", "digits", "satimage")
METHODS = ("granular_ball", "kmeans", "error_tree", "knn_density", "random_cells")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [json.loads(line) for line in RESULTS.read_text().splitlines() if line]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 12 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 12 successful records, got {len(records)}")
    summary = {}
    for dataset in DATASETS:
        subset = [record for record in records if record["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {}
        for method in METHODS:
            values = [
                next(point for point in record["additional_metrics"]["frontier"] if point["method"] == method)
                for record in subset
            ]
            summary[dataset][method] = {
                "uplift": mean(point["risk_uplift"] for point in values),
                "recall": mean(point["error_recall"] for point in values),
                "hidden": mean(point["hidden_region_precision"] for point in values),
            }
    uplift_gap = mean(record["additional_metrics"]["risk_uplift_gap_vs_best"] for record in records)
    recall_gap = mean(record["additional_metrics"]["error_recall_gap_vs_best"] for record in records)
    uplift_passes = sum(record["additional_metrics"]["risk_uplift_gap_vs_best"] >= 0.05 for record in records)
    recall_passes = sum(record["additional_metrics"]["error_recall_gap_vs_best"] >= 0.05 for record in records)
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['uplift']:.3f}" for method in METHODS)
        + f" | {summary[dataset]['granular_ball']['recall']:.3f} |"
        for dataset in DATASETS
    )
    report = f"""# GB application: model failure-slice discovery

Generated by `python scripts/analyze_app_failure_slices.py`. Audit date:
2026-08-25.

## Decision

**`REJECT`.** At fixed 20% audit coverage, GB risk uplift is
{abs(uplift_gap):.3f} below the strongest slice baseline and error recall is
{abs(recall_gap):.3f} lower on average. The +5 pp uplift gate passes
{uplift_passes}/12 and recall gate passes {recall_passes}/12.

## Frozen evidence

- Four datasets x three seeds with a hidden nonlinear feature-corruption region.
- A fixed LogisticRegression creates validation/test errors. Slice models see
  validation features and error indicators only; test labels remain hidden.
- GB, matched KMeans, error tree, kNN error density and random-projection cells
  all select exactly about 20% of test items via validation-estimated risk.

| Dataset | GB uplift | KMeans | Error tree | kNN density | Random cells | GB error recall |
|---|---:|---:|---:|---:|---:|---:|
{table}

KMeans or kNN error density is stronger on every dataset-level mean. GB is
competitive on Satimage but does not transfer. The application is also close to
generic slice discovery and the repository's earlier local-risk work; do not
tune purity or corruption strength.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "uplift_gap": uplift_gap, "recall_gap": recall_gap, "uplift_passes": uplift_passes, "recall_passes": recall_passes, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
