"""Analyze the frozen fixed-region approximate-unlearning application test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/local_unlearning_report.md"
STUDY = "granular-ball-application-local-unlearning"
DATASETS = ("breast_cancer", "wine", "digits", "satimage")
METHODS = ("granular_ball", "kmeans", "decision_tree")
SCENARIOS = ("random", "local_concentrated", "class_skew")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [json.loads(line) for line in RESULTS.read_text().splitlines() if line]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 12 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 12 successful records, got {len(records)}")
    summary = {}
    for dataset in DATASETS:
        subset = [record for record in records if record["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {}
        for method in METHODS:
            values = [
                next(point for point in record["additional_metrics"]["frontier"] if point["method"] == method and point["scenario"] == "local_concentrated")
                for record in subset
            ]
            summary[dataset][method] = {
                "agreement": mean(point["agreement_with_full_retrain"] for point in values),
                "l1": mean(point["probability_l1_vs_full"] for point in values),
                "accuracy_gap": mean(point["accuracy_gap_vs_full"] for point in values),
                "speedup": mean(point["speedup"] for point in values),
            }
    agreement_gap = mean(record["additional_metrics"]["agreement_gap_vs_best"] for record in records)
    positive = sum(record["additional_metrics"]["agreement_gap_vs_best"] >= 0.01 for record in records)
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['agreement']:.3f}" for method in METHODS)
        + f" | {summary[dataset]['granular_ball']['speedup']:.1f}x |"
        for dataset in DATASETS
    )
    report = f"""# GB application: fixed-region approximate unlearning

Generated by `python scripts/analyze_app_local_unlearning.py`. Audit date:
2026-08-25.

## Decision

**`REJECT`.** Under local-concentrated 10% deletion, GB prediction agreement with
its own full retrain is {abs(agreement_gap):.3f} below the strongest matched
fixed-region updater on average. A +1 pp agreement advantage appears in
{positive}/12 runs.

## Frozen evidence

- Four datasets x three seeds; random, local-concentrated and class-skew deletion.
- Each approximate method keeps its initial regional assignment and recomputes
  only affected sufficient statistics. Its own complete post-deletion rebuild is
  the reference.
- Matched methods are GB, equal-count KMeans regions and decision-tree-derived
  regional prototypes.

| Dataset | GB agreement | KMeans | Tree regions | GB speedup |
|---|---:|---:|---:|---:|
{table}

GB achieves very large speedups on Breast Cancer and useful speedups elsewhere,
but KMeans/tree regions match or improve post-retrain fidelity, especially on
Digits and Satimage. The speed benefit is localized sufficient-statistic update,
not a unique GB advantage.

This experiment is approximate deletion only. It provides no certified
unlearning, privacy guarantee, membership-inference audit or removal certificate.
Do not promote or expand it as machine unlearning.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "agreement_gap": agreement_gap, "passes": positive, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
