"""Analyze the frozen learnable anisotropic cross-view application test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/learnable_cross_view_report.md"
STUDY = "granular-ball-application-learnable-cross-view"
DATASETS = ("satimage", "digits", "breast_cancer", "wine")
METHODS = ("anisotropic_gb", "isotropic_prototype", "mlp_imputer", "fixed_kmeans", "ridge", "visible_only")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [json.loads(line) for line in RESULTS.read_text().splitlines() if line]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 12 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 12 successful records, got {len(records)}")
    summary = {}
    for dataset in DATASETS:
        subset = [record for record in records if record["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {}
        for method in METHODS:
            values = [
                next(point for point in record["additional_metrics"]["frontier"] if point["method"] == method and point["missing_rate"] == 0.40)
                for record in subset
            ]
            summary[dataset][method] = {
                "rmse": mean(point["imputation_nrmse"] for point in values),
                "accuracy": mean(point["accuracy"] for point in values),
                "seconds": mean(point["training_seconds"] for point in values),
                "parameters": mean(point["parameters"] for point in values),
            }
    rmse_gain = mean(record["additional_metrics"]["relative_rmse_gain_vs_best"] for record in records)
    accuracy_gap = mean(record["additional_metrics"]["accuracy_gap_vs_best"] for record in records)
    rmse_passes = sum(record["additional_metrics"]["relative_rmse_gain_vs_best"] >= 0.05 for record in records)
    accuracy_passes = sum(record["additional_metrics"]["accuracy_gap_vs_best"] >= 0.01 for record in records)
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['rmse']:.3f}" for method in METHODS)
        + f" | {summary[dataset]['anisotropic_gb']['accuracy']:.3f} |"
        for dataset in DATASETS
    )
    report = f"""# GB application: learnable anisotropic cross-view recovery

Generated by `python scripts/analyze_app_learnable_cross_view.py`. Audit date:
2026-08-25.

## Decision

**`REJECT`.** At 40% missing items, the learnable anisotropic GB has
{abs(rmse_gain):.1%} worse imputation NRMSE and {abs(accuracy_gap):.2%} lower
classification accuracy than the best matched method on average. The +5%
recovery gate passes {rmse_passes}/12 and +1 pp accuracy gate passes
{accuracy_passes}/12.

## Frozen evidence

- Four datasets x three seeds, trained for 80 full-batch epochs on Apple MPS.
- Learnable centers, per-dimension scales, cross-view prototypes and a classifier
  are optimized jointly with reconstruction and classification loss.
- Baselines: learnable isotropic prototypes, equal-budget MLP imputer, fixed
  KMeans prototypes, Ridge and visible-view-only prediction.

| Dataset | Anisotropic GB NRMSE | Isotropic | MLP | KMeans | Ridge | Visible only | GB accuracy |
|---|---:|---:|---:|---:|---:|---:|---:|
{table}

MLP or Ridge is strongest on every dataset. Anisotropy occasionally improves the
isotropic prototype but does not close the generic function-approximation gap.
This is an AD-GBC-inspired mechanism transfer, not a reproduction of its medical
segmentation result; the negative finding is limited to cross-view recovery.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "rmse_gain": rmse_gain, "accuracy_gap": accuracy_gap, "rmse_passes": rmse_passes, "accuracy_passes": accuracy_passes, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
