"""Analyze the frozen inference-time missing-view recovery test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/missing_view_report.md"
STUDY = "granular-ball-application-missing-view"
DATASETS = ("satimage", "digits", "breast_cancer", "wine")
METHODS = ("gb_multiscale", "gb_terminal", "kmeans", "knn", "decision_tree", "ridge", "global_mean")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [json.loads(line) for line in RESULTS.read_text().splitlines() if line]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 12 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 12 successful records, got {len(records)}")
    summary = {}
    for dataset in DATASETS:
        subset = [record for record in records if record["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {}
        for method in METHODS:
            values = [
                next(point for point in record["additional_metrics"]["frontier"] if point["method"] == method and point["missing_rate"] == 0.40)
                for record in subset
            ]
            summary[dataset][method] = {
                "rmse": mean(point["imputation_nrmse"] for point in values),
                "accuracy": mean(point["accuracy"] for point in values),
                "worst": mean(point["worst_class_missing_accuracy"] for point in values),
            }
    rmse_gain = mean(record["additional_metrics"]["relative_rmse_gain_vs_best"] for record in records)
    accuracy_gap = mean(record["additional_metrics"]["accuracy_gap_vs_best"] for record in records)
    rmse_passes = sum(record["additional_metrics"]["relative_rmse_gain_vs_best"] >= 0.05 for record in records)
    accuracy_passes = sum(record["additional_metrics"]["accuracy_gap_vs_best"] >= 0.01 for record in records)
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['rmse']:.3f}" for method in METHODS)
        + f" | {summary[dataset]['gb_multiscale']['accuracy']:.3f} |"
        for dataset in DATASETS
    )
    report = f"""# GB application: inference-time missing-view recovery

Generated by `python scripts/analyze_app_missing_view.py`. Audit date:
2026-08-25.

## Decision

**`REJECT` the fixed-region recovery mechanism.** At 40% missing items, GB
multiscale imputation NRMSE is {abs(rmse_gain):.1%} worse than the best recovery
baseline and classification accuracy is {abs(accuracy_gap):.2%} lower on
average. The +5% recovery gate passes {rmse_passes}/12 and +1 pp accuracy gate
passes {accuracy_passes}/12.

## Frozen evidence

- Satimage, Digits, Breast Cancer and Wine x three seeds.
- Views are deterministic feature halves. Training is complete; one view is
  hidden from 20/40/60% of test items.
- The same fixed classifier receives recovered features from GB multiscale,
  terminal GB, KMeans regions, kNN, tree, Ridge or global-mean imputation.

| Dataset | GB multi NRMSE | GB terminal | KMeans | kNN | Tree | Ridge | Mean | GB accuracy |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
{table}

Ridge or kNN is strongest on every dataset. Terminal GB often matches or beats
multiscale GB, showing that averaging more fixed regions does not create useful
cross-view semantics. This motivates a separate learnable-region test rather
than tuning the fixed partition.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "rmse_gain": rmse_gain, "accuracy_gap": accuracy_gap, "rmse_passes": rmse_passes, "accuracy_passes": accuracy_passes, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
