"""Analyze the frozen contextual cell-cleaning application kill test."""

from __future__ import annotations

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/cell_cleaning_report.md"
STUDY = "granular-ball-application-cell-cleaning"
DATASETS = ("breast_cancer", "wine", "diabetes")
SEEDS = (1, 7, 21, 42, 2026)
METHODS = (
    "gb_surface_multiscale",
    "gb_center_multiscale",
    "kmeans_multiscale",
    "knn_context",
    "decision_tree",
    "global_robust",
)


def mean(values):
    return statistics.fmean(values)


def method_row(record, method):
    matches = [row for row in record["additional_metrics"]["methods"] if row["method"] == method]
    if len(matches) != 1:
        raise ValueError(f"{record['experiment_id']}: missing {method}")
    return matches[0]


def load():
    records = [
        json.loads(line)
        for line in RESULTS.read_text(encoding="utf-8").splitlines()
        if line
    ]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 15 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 15 successful records, got {len(records)}")
    observed = {
        (record["dataset_generation_parameters"]["dataset"], int(record["seed"]))
        for record in records
    }
    if observed != {(dataset, seed) for dataset in DATASETS for seed in SEEDS}:
        raise ValueError("cell-cleaning grid mismatch")
    return records


def main():
    records = load()
    summary = {}
    for dataset in DATASETS:
        subset = [r for r in records if r["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {
            method: {
                "auprc": mean(method_row(r, method)["cell_auprc"] for r in subset),
                "precision": mean(
                    method_row(r, method)["precision_at_review_budget"] for r in subset
                ),
                "repair_mae": mean(
                    method_row(r, method)["normalized_mae_corrupted_cells"] for r in subset
                ),
                "downstream_delta": mean(
                    method_row(r, method)["downstream_delta_vs_dirty"] for r in subset
                ),
            }
            for method in METHODS
        }
    gaps = [r["additional_metrics"]["cell_auprc_gap_vs_best_reference"] for r in records]
    ablation_gaps = [
        r["additional_metrics"]["cell_auprc_gap_vs_center_ablation"] for r in records
    ]
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['auprc']:.3f}" for method in METHODS)
        + " |"
        for dataset in DATASETS
    )
    report = f"""# GB application: contextual cell-error cleaning

Generated by `python scripts/analyze_app_cell_cleaning.py` from the append-only
ledger. Audit date: 2026-08-25.

## Decision

**`REJECT`.** The first contextual corruption kill test fails both the application
and granular-ball attribution gates. GB trails the strongest per-run baseline by
{abs(mean(gaps)):.3f} cell AUPRC on average and wins by at least .03 in
{sum(gap >= .03 for gap in gaps)}/15 runs. Radius-aware multiscale routing trails
the identical bisecting-tree center-only ablation by {abs(mean(ablation_gaps)):.3f}
AUPRC and wins by at least .02 in {sum(gap >= .02 for gap in ablation_gaps)}/15.

## Frozen protocol

- Three local sklearn numeric tables x five seeds = 15 successful CPU runs.
- Only outer-train cells are corrupted; outer-test rows remain clean.
- Every training cell is scored out of fold. Context construction and routing for
  column `j` exclude `x_j`; class/regression targets never enter granulation.
- Corrupted values are copied from a contextually distant local group in the same
  held-out fold, preserving marginal plausibility.
- Review/repair budget equals the fixed 3% corruption rate. False-positive edits
  are included in repair and downstream metrics.

Mean cell AUPRC over five seeds:

| Dataset | GB surface | Same-tree center | Multi-K KMeans | kNN | Tree | Global |
|---|---:|---:|---:|---:|---:|---:|
{table}

On breast cancer, kNN reaches {summary['breast_cancer']['knn_context']['auprc']:.3f}
versus {summary['breast_cancer']['gb_surface_multiscale']['auprc']:.3f} for GB.
On diabetes, the decision tree reaches
{summary['diabetes']['decision_tree']['auprc']:.3f} versus
{summary['diabetes']['gb_surface_multiscale']['auprc']:.3f}. Wine is weak for all
methods, but GB still trails kNN/tree and the same-tree center ablation.

## Repair and attribution

At the fixed review budget, GB precision is
{summary['breast_cancer']['gb_surface_multiscale']['precision']:.3f} on breast
cancer, compared with {summary['breast_cancer']['knn_context']['precision']:.3f}
for kNN. Its corrupted-cell normalized MAE is
{summary['breast_cancer']['gb_surface_multiscale']['repair_mae']:.3f}, versus
{summary['breast_cancer']['knn_context']['repair_mae']:.3f} for kNN.

The mandatory same-partition ablation closes the claim: replacing normalized
surface routing with center routing improves rather than harms mean AUPRC. Any
residual benefit belongs to robust local statistics or hierarchical 2-means, not
to a granular-ball radius mechanism.

## Kill rationale

- Zero of 15 runs clear the +.03 strongest-baseline AUPRC gate.
- Zero of 15 clear the +.02 same-tree radius-attribution gate.
- Strong kNN/tree baselines also repair corrupted cells more accurately.
- Only one synthetic corruption has been run, but expanding to easier gross
  errors cannot repair the failed granular-ball attribution gate.

Do not add corruption types, real tables, or tune radius/split/MAD choices. The
next application test is hard-budget local regranulation in streams.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "mean_gap": mean(gaps), "ablation_gap": mean(ablation_gaps), "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
