"""Analyze the frozen granular-ball spatial sensor placement test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/sensor_placement_report.md"
STUDY = "granular-ball-application-sensor-placement"
FAMILIES = ("smooth_multiscale", "anisotropic", "discontinuous", "local_hotspots")
METHODS = ("granular_ball", "kmeans", "kcenter", "facility_location", "axis_tree", "random")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [
        json.loads(line)
        for line in RESULTS.read_text(encoding="utf-8").splitlines()
        if line
    ]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 20 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 20 successful records, got {len(records)}")
    rows = {}
    for family in FAMILIES:
        subset = [record for record in records if record["dataset_generation_parameters"]["family"] == family]
        rows[family] = {}
        for method in METHODS:
            values = [
                next(
                    point
                    for point in record["additional_metrics"]["frontier"]
                    if point["method"] == method and point["fraction"] == 0.10
                )
                for record in subset
            ]
            rows[family][method] = {
                "rmse": mean(point["normalized_rmse"] for point in values),
                "worst": mean(point["worst_region_rmse"] for point in values),
                "milliseconds": 1000 * mean(point["selection_seconds"] for point in values),
            }
    passes = sum(
        record["additional_metrics"]["relative_rmse_gain_vs_best"] >= 0.05
        and record["additional_metrics"]["relative_worst_region_gain_vs_best"] >= 0.05
        for record in records
    )
    rmse_gain = mean(record["additional_metrics"]["relative_rmse_gain_vs_best"] for record in records)
    worst_gain = mean(
        record["additional_metrics"]["relative_worst_region_gain_vs_best"] for record in records
    )
    table = "\n".join(
        f"| {family} | "
        + " | ".join(f"{rows[family][method]['rmse']:.4f}" for method in METHODS)
        + f" | {rows[family]['granular_ball']['worst']:.4f} |"
        for family in FAMILIES
    )
    report = f"""# GB application: spatial sensor placement

Generated by `python scripts/analyze_app_sensor_placement.py`. Audit date:
2026-08-25.

## Decision

**`REJECT`.** At a fixed 10% station budget, GB mean RMSE gain over the strongest
matched selector is {rmse_gain:+.2%}; worst-region gain is {worst_gain:+.2%}.
The joint +5% gate passes in {passes}/20 runs.

## Frozen evidence

- Four heterogeneous spatial-field families x five seeds, 400 candidate sites,
  48 historical and 24 future snapshots.
- Selection sees coordinates and historical temporal PCA only. Future values are
  hidden until evaluation.
- A single fixed Ridge reconstruction model maps selected historical/future
  station values to unobserved stations.
- Baselines: matched KMeans medoids, k-center, facility location, axis tree and
  random sites. Sensor budgets are 5%, 10% and 20%.

Mean normalized RMSE at 10% budget:

| Family | GB | KMeans | k-center | Facility | Axis tree | Random | GB worst-region RMSE |
|---|---:|---:|---:|---:|---:|---:|---:|
{table}

GB is competitive with KMeans/axis selection and beats them on some local-
hotspot mean-RMSE cells, but facility/k-center or axis methods retain lower
worst-region error. GB selection is also slower: roughly 40-43 ms at 10%, versus
about 16-18 ms for KMeans and 4-6 ms for facility/axis selection.

Only synthetic fields were used. Real-station expansion is not justified after
the matched-selector gate fails. Do not tune field-aware split scores on this
grid.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "passes": passes, "rmse_gain": rmse_gain, "worst_gain": worst_gain, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
