"""Analyze the frozen grouped training-data valuation application test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/group_valuation_report.md"
STUDY = "granular-ball-application-group-valuation"
DATASETS = ("breast_cancer", "wine", "digits", "moons")
METHODS = ("granular_ball", "kmeans", "decision_tree", "random_groups")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [json.loads(line) for line in RESULTS.read_text().splitlines() if line]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 12 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 12 successful records, got {len(records)}")
    summary = {}
    for dataset in DATASETS:
        subset = [record for record in records if record["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {}
        for method in METHODS:
            values = [
                next(point for point in record["additional_metrics"]["methods"] if point["method"] == method)
                for record in subset
            ]
            summary[dataset][method] = {
                "correlation": mean(point["spearman_exact_influence"] for point in values),
                "overlap": mean(point["top_harmful_overlap"] for point in values),
                "noise": mean(point["noise_auprc"] for point in values),
                "retrains": mean(point["retrains"] for point in values),
            }
    correlation_gap = mean(record["additional_metrics"]["correlation_gap_vs_best"] for record in records)
    noise_gap = mean(record["additional_metrics"]["noise_auprc_gap_vs_best"] for record in records)
    reduction = mean(record["additional_metrics"]["retrain_reduction_vs_exact"] for record in records)
    correlation_passes = sum(
        record["additional_metrics"]["correlation_gap_vs_best"] >= 0.05 for record in records
    )
    noise_passes = sum(record["additional_metrics"]["noise_auprc_gap_vs_best"] >= 0.03 for record in records)
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['correlation']:.3f}" for method in METHODS)
        + f" | {summary[dataset]['granular_ball']['noise']:.3f} |"
        for dataset in DATASETS
    )
    report = f"""# GB application: grouped training-data valuation

Generated by `python scripts/analyze_app_group_valuation.py`. Audit date:
2026-08-25.

## Decision

**`REJECT`.** Grouped leave-out reduces retraining by {reduction:.1%}, but this
gain is shared by every partition baseline. GB trails the best matched grouping
by {abs(correlation_gap):.3f} Spearman correlation to exact leave-one-out and
{abs(noise_gap):.3f} noise AUPRC. The +.05 correlation gate passes
{correlation_passes}/12 and +.03 noise gate passes {noise_passes}/12.

## Frozen evidence

- Four classification datasets x three seeds, capped at 320 rows with 10% label
  corruption.
- Exact leave-one-out validation-loss influence is the reference.
- GB, matched-K KMeans, decision-tree leaves and random balanced groups all map a
  group-removal effect back to member points under the same retrain count.

| Dataset | GB Spearman | KMeans | Tree | Random groups | GB noise AUPRC |
|---|---:|---:|---:|---:|---:|
{table}

GB produces useful correlation on some cells, especially Moons, but supervised
tree leaves are stronger on Breast Cancer, Wine and Moons; random/KMeans grouping
is stronger on Digits. Tree leaves also dominate wrong-label identification.

The resource result belongs to grouped valuation generally. Do not tune purity
or reinterpret approximate influence correlation as a new noise-cleaning method.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "correlation_gap": correlation_gap, "noise_gap": noise_gap, "retrain_reduction": reduction, "correlation_passes": correlation_passes, "noise_passes": noise_passes, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
