"""Analyze the frozen fixed-slot visual/spectral gallery retrieval test."""

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/gallery_retrieval_report.md"
STUDY = "granular-ball-application-gallery-retrieval"
DATASETS = ("satimage", "satellite", "covertype", "digits")
METHODS = ("granular_ball", "kmeans", "kcenter", "axis_tree", "random", "full")


def mean(values):
    return statistics.fmean(values)


def main():
    records = [
        json.loads(line)
        for line in RESULTS.read_text(encoding="utf-8").splitlines()
        if line
    ]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 12 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 12 successful records, got {len(records)}")
    summary = {}
    for dataset in DATASETS:
        subset = [record for record in records if record["dataset_generation_parameters"]["dataset"] == dataset]
        summary[dataset] = {}
        for method in METHODS:
            values = []
            for record in subset:
                values.append(
                    next(
                        point
                        for point in record["additional_metrics"]["frontier"]
                        if point["method"] == method
                        and (method == "full" or point["fraction"] == 0.10)
                    )
                )
            summary[dataset][method] = {
                "map": mean(point["map_at_10"] for point in values),
                "rare": mean(point["rare_hit_at_10"] for point in values),
                "query_ms": 1000 * mean(point["query_seconds"] for point in values),
                "selection_ms": 1000 * mean(point["selection_seconds"] for point in values),
            }
    map_passes = sum(record["additional_metrics"]["map_gap_vs_best"] >= 0.02 for record in records)
    rare_passes = sum(record["additional_metrics"]["rare_hit_gap_vs_best"] >= 0.02 for record in records)
    joint_passes = sum(
        record["additional_metrics"]["map_gap_vs_best"] >= 0.02
        and record["additional_metrics"]["rare_hit_gap_vs_best"] >= 0.02
        for record in records
    )
    map_gap = mean(record["additional_metrics"]["map_gap_vs_best"] for record in records)
    rare_gap = mean(record["additional_metrics"]["rare_hit_gap_vs_best"] for record in records)
    table = "\n".join(
        f"| {dataset} | "
        + " | ".join(f"{summary[dataset][method]['map']:.3f}" for method in METHODS)
        + f" | {summary[dataset]['granular_ball']['rare']:.3f} |"
        for dataset in DATASETS
    )
    report = f"""# GB application: fixed-slot gallery retrieval

Generated by `python scripts/analyze_app_gallery_retrieval.py`. Audit date:
2026-08-25.

## Decision

**`REJECT` the current gallery selector.** At 10% gallery slots, GB trails the
best matched selector by {abs(map_gap):.3f} mAP@10 and {abs(rare_gap):.3f}
rare-class Hit@10 on average. The +2 pp mAP gate passes in {map_passes}/12,
rare-hit in {rare_passes}/12, and jointly in {joint_passes}/12.

## Frozen evidence

- Three OpenML spectral/cartographic datasets plus Digits, three seeds each.
- Each dataset is capped at 2,400 items, split 70% gallery / 30% query, scaled and
  projected to a 16-dimensional frozen PCA space.
- Selection is unsupervised. All methods use the same slots and exact reranking:
  GB medoids, KMeans medoids, k-center, axis tree and random. Full exact gallery
  is an upper bound.
- 10% slots reduce exact distance computations by 90% for every compressed
  method; this resource gain is not GB-specific.

Mean mAP@10 at 10% slots:

| Dataset | GB | KMeans | k-center | Axis tree | Random | Full | GB rare Hit@10 |
|---|---:|---:|---:|---:|---:|---:|---:|
{table}

Satimage contains an isolated positive seed and GB's mean mAP is competitive,
but random selection is stronger on average. Digits shows a small GB mean mAP
advantage over compressed baselines (+0.28 pp versus random), below the 2 pp
gate. Rare-class coverage is consistently explained better by KMeans, k-center
or random selection. GB construction also costs roughly 0.2-0.34 seconds versus
about 0.06-0.10 seconds for KMeans.

Do not tune a class-aware selection score: labels were intentionally excluded
from gallery construction. A supervised rare-class selector would be a different
application contract.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "map_passes": map_passes, "rare_passes": rare_passes, "joint_passes": joint_passes, "map_gap": map_gap, "rare_gap": rare_gap, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
