"""Analyze the frozen hard-budget online granular-ball application test."""

from __future__ import annotations

import json
import statistics
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "experiments/results/experiments.jsonl"
REPORT = ROOT / "reports/application_exploration/online_memory_report.md"
STUDY = "granular-ball-application-online-memory"
KINDS = ("concept_drift", "covariate_shift", "emerging_class")
SEEDS = (1, 7, 21)
METHODS = ("gb_surface", "center_ablation", "sliding_gbc", "sgd")


def mean(values):
    return statistics.fmean(values)


def load():
    records = [
        json.loads(line)
        for line in RESULTS.read_text(encoding="utf-8").splitlines()
        if line
    ]
    records = [record for record in records if record.get("study") == STUDY]
    if len(records) != 9 or any(record.get("outcome") != "success" for record in records):
        raise ValueError(f"expected 9 successful records, got {len(records)}")
    observed = {
        (record["dataset_generation_parameters"]["stream_kind"], int(record["seed"]))
        for record in records
    }
    if observed != {(kind, seed) for kind in KINDS for seed in SEEDS}:
        raise ValueError("online-memory grid mismatch")
    return records


def main():
    records = load()
    summary = {}
    for kind in KINDS:
        subset = [r for r in records if r["dataset_generation_parameters"]["stream_kind"] == kind]
        summary[kind] = {
            method: {
                "accuracy": mean(r["additional_metrics"]["methods"][method]["accuracy"] for r in subset),
                "macro_f1": mean(r["additional_metrics"]["methods"][method]["macro_f1"] for r in subset),
                "update_ms": 1000 * mean(
                    r["additional_metrics"]["methods"][method]["mean_update_seconds"]
                    for r in subset
                ),
            }
            for method in METHODS
        }
    table = "\n".join(
        f"| {kind} | "
        + " | ".join(f"{summary[kind][method]['accuracy']:.3f}" for method in METHODS)
        + " | "
        + " | ".join(f"{summary[kind][method]['update_ms']:.3f}" for method in METHODS[::2])
        + " |"
        for kind in KINDS
    )
    risk_passes = sum(
        r["additional_metrics"]["accuracy_gap_vs_best_reference"] >= -0.01 for r in records
    )
    attribution_passes = sum(
        r["additional_metrics"]["accuracy_gap_vs_center_ablation"] >= 0.01 for r in records
    )
    time_passes = sum(
        r["additional_metrics"]["update_time_ratio_vs_sliding"] <= 0.20 for r in records
    )
    report = f"""# GB application: hard-budget online local memory

Generated by `python scripts/analyze_app_online_memory.py` from the append-only
ledger. Audit date: 2026-08-25.

## Decision

**`REJECT` as a granular-ball application.** The local state is fast and compact,
but it fails the joint risk, update-time and radius-attribution gates. Risk is
within 1 pp of the best sliding/SGD reference in {risk_passes}/9 runs; update time
is at most 20% of sliding rebuild in {time_passes}/9; radius-aware prediction
beats the identical state with center-only prediction by 1 pp in
{attribution_passes}/9.

## Frozen protocol

- Three streams x three seeds = nine successful prequential CPU runs.
- The candidate maintains at most 24 local states containing center, radius,
  class counts, weight and age; it updates only assigned regions, creates local
  states for conflicts/support escape, expires stale states and merges same-class
  states at the cap.
- The center-only ablation reads the exact same state. Sliding GBC rebuild and
  online SGD are trained on the same predict-before-update batches.

| Stream | GB Accuracy | Center Accuracy | Sliding Accuracy | SGD Accuracy | GB update ms | Sliding update ms |
|---|---:|---:|---:|---:|---:|---:|
{table}

## Interpretation

- Concept drift: generic local state is useful, but center-only reaches
  {summary['concept_drift']['center_ablation']['accuracy']:.3f}, versus
  {summary['concept_drift']['gb_surface']['accuracy']:.3f} for surface routing
  and {summary['concept_drift']['sgd']['accuracy']:.3f} for SGD.
- Covariate shift: GB is fast but misses the 1 pp risk gate
  ({summary['covariate_shift']['gb_surface']['accuracy']:.3f} versus
  {summary['covariate_shift']['sgd']['accuracy']:.3f}) and consumes about half
  the already cheap sliding-update time rather than the required 20%.
- Emerging class: GB nearly matches SGD
  ({summary['emerging_class']['gb_surface']['accuracy']:.3f} versus
  {summary['emerging_class']['sgd']['accuracy']:.3f}), but center-only is slightly
  better and recent open-world/incremental GB papers directly occupy the role.

The strongest positive observation is therefore generic: bounded local
prototypes can replace costly full/sliding GBC rebuild on concept drift. Radius
geometry does not improve that state, so it cannot support a granular-ball claim.

## Kill rationale

- The required joint gate fails in two of three streams.
- Surface routing never clears the same-state +1 pp attribution gate.
- Local create/update/merge/expire is directly adjacent to ILAGBRS, EG-CNN and
  adaptive model-refresh work.
- Tuning cap, EMA or expiry on these nine cells would be post-hoc and cannot fix
  the failed radius attribution.

No additional split/merge tuning or real-stream expansion is allowed. Batch
active learning is the remaining low-compute application candidate.
"""
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report, encoding="utf-8")
    print(json.dumps({"records": len(records), "decision": "REJECT", "risk_passes": risk_passes, "time_passes": time_passes, "attribution_passes": attribution_passes, "report": str(REPORT.relative_to(ROOT))}))


if __name__ == "__main__":
    main()
